Add prerequisities of login/signup
chizmiz-project/front pull request #3
Opened 2024-12-27 13:25 UTC by Soltaniant

2025-01-01 04:51 UTC, ali-bonaftizadeh requested changes

2025-01-01 04:51 UTC, ali-bonaftizadeh commented on src/App.js
> +            {/* <Route path="/recent-views" element={<RecentViews />} /> */}
why commented? remove if not needed.

2025-01-01 04:51 UTC, ali-bonaftizadeh commented on src/layouts/settingPage.js
> +          }}
why is the user data hard coded?

2025-01-01 04:51 UTC, ali-bonaftizadeh commented on src/components/AppBar.js
> +        <Typography variant="h6" component="h1" style={{
The inline styles applied to center the Typography component could be replaced by a more maintainable approach, such as using MUI's sx prop or CSS classes.

2025-01-01 04:51 UTC, ali-bonaftizadeh commented on src/components/setting/settingItem.js
> +            </ListItem>
The current implementation repeats similar code for rendering ListItemText and secondaryAction. Consider extracting common logic to reduce redundancy.

2025-01-02 04:17 UTC, Soltaniant commented on src/layouts/settingPage.js
> +          }}
temp test.
will be removed after completing the login process.

2025-01-02 04:18 UTC, Soltaniant commented on src/components/setting/settingItem.js
> +            </ListItem>
done in later merges

2025-01-02 04:18 UTC, merged