Redesign All Ads section + categories
chizmiz-project/front pull request #4
Opened 2024-12-27 16:16 UTC by Soltaniant

2025-01-01 04:53 UTC, ali-bonaftizadeh requested changes

2025-01-01 04:53 UTC, ali-bonaftizadeh commented on src/App.js
>              {/* <Route path="/recent-views" element={<RecentViews />} /> */}
remove commented code.

2025-01-01 04:53 UTC, ali-bonaftizadeh commented on src/layouts/MainPage.js
> +]
??

2025-01-01 04:53 UTC, ali-bonaftizadeh commented on src/components/CategoryItem.js
> +        cursor: 'pointer'
Consider using the sx prop instead of style for better integration with Material-UI's styling system.

2025-01-02 04:15 UTC, Soltaniant commented on src/App.js
>              {/* <Route path="/recent-views" element={<RecentViews />} /> */}
done

2025-01-02 04:15 UTC, Soltaniant commented on src/layouts/MainPage.js
> +]
temporarily created for test.
after adding the API calls will be removed

2025-01-02 04:15 UTC, Soltaniant commented on src/components/CategoryItem.js
> +        cursor: 'pointer'
done

2025-01-02 04:17 UTC, merged